-- 法語單詞備用干擾選項池（distractor fallback pool）
-- 總計：613 筆（A1: 337, A2: 175, B1: 101）
-- 用途：測驗題目無法從學習詞彙池取得足夠干擾選項時使用

-- ============================================================
-- A1 Words (337 筆)
-- ============================================================

-- 星期（7）
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('lundi', 'Monday', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('mardi', 'Tuesday', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('mercredi', 'Wednesday', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('jeudi', 'Thursday', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('vendredi', 'Friday', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('samedi', 'Saturday', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('dimanche', 'Sunday', 'A1');

-- 月份（12）
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('janvier', 'January', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('février', 'February', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('mars', 'March', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('avril', 'April', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('mai', 'May', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('juin', 'June', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('juillet', 'July', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('août', 'August', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('septembre', 'September', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('octobre', 'October', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('novembre', 'November', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('décembre', 'December', 'A1');

-- 數字（文字形式）（25）
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('un', 'one', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('deux', 'two', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('trois', 'three', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('quatre', 'four', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('cinq', 'five', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('six', 'six', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('sept', 'seven', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('huit', 'eight', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('neuf', 'nine', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('dix', 'ten', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('onze', 'eleven', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('douze', 'twelve', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('treize', 'thirteen', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('quatorze', 'fourteen', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('quinze', 'fifteen', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('seize', 'sixteen', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('dix-sept', 'seventeen', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('dix-huit', 'eighteen', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('dix-neuf', 'nineteen', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('vingt', 'twenty', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('trente', 'thirty', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('quarante', 'forty', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('cinquante', 'fifty', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('cent', 'one hundred', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('mille', 'one thousand', 'A1');

-- 顏色（15）
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('rouge', 'red', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('bleu', 'blue', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('vert', 'green', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('jaune', 'yellow', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('blanc', 'white', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('noir', 'black', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('orange', 'orange', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('violet', 'purple', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('rose', 'pink', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('gris', 'grey', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('marron', 'brown', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('beige', 'beige', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('doré', 'golden', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('argenté', 'silver', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('turquoise', 'turquoise', 'A1');

-- 家庭成員（20）
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('père', 'father', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('mère', 'mother', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('frère', 'brother', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('sœur', 'sister', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('grand-père', 'grandfather', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('grand-mère', 'grandmother', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('fils', 'son', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('fille', 'daughter', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('oncle', 'uncle', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('tante', 'aunt', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('cousin', 'cousin (male)', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('cousine', 'cousin (female)', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('mari', 'husband', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('femme', 'wife / woman', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('enfant', 'child', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('bébé', 'baby', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('famille', 'family', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('parent', 'parent', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('neveu', 'nephew', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('nièce', 'niece', 'A1');

-- 食物與飲料（39）注意：orange 已在顏色，用 thon 取代 poisson（poisson 在動物）
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('pain', 'bread', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('eau', 'water', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('lait', 'milk', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('jus', 'juice', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('café', 'coffee', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('thé', 'tea', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('vin', 'wine', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('bière', 'beer', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('fromage', 'cheese', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('beurre', 'butter', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('pomme', 'apple', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('banane', 'banana', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('citron', 'lemon', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('raisin', 'grape', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('fraise', 'strawberry', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('tomate', 'tomato', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('carotte', 'carrot', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('pomme de terre', 'potato', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('salade', 'salad / lettuce', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('viande', 'meat', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('poulet', 'chicken', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('thon', 'tuna', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('œuf', 'egg', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('soupe', 'soup', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('riz', 'rice', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('pâtes', 'pasta', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('sandwich', 'sandwich', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('gâteau', 'cake', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('sucre', 'sugar', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('sel', 'salt', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('huile', 'oil', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('yaourt', 'yoghurt', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('crème', 'cream', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('glace', 'ice cream', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('pizza', 'pizza', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('burger', 'burger', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('céréales', 'cereal', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('confiture', 'jam', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('chocolat', 'chocolate', 'A1');

-- 動物（25）
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('chat', 'cat', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('chien', 'dog', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('oiseau', 'bird', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('poisson', 'fish', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('lapin', 'rabbit', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('cheval', 'horse', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('vache', 'cow', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('cochon', 'pig', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('mouton', 'sheep', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('poule', 'hen', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('canard', 'duck', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('souris', 'mouse', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('rat', 'rat', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('lion', 'lion', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('tigre', 'tiger', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('éléphant', 'elephant', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('girafe', 'giraffe', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('singe', 'monkey', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('serpent', 'snake', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('grenouille', 'frog', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('tortue', 'turtle', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('papillon', 'butterfly', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('abeille', 'bee', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('fourmi', 'ant', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('araignée', 'spider', 'A1');

-- 身體部位（20）
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('tête', 'head', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('œil', 'eye', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('oreille', 'ear', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('nez', 'nose', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('bouche', 'mouth', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('dent', 'tooth', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('cou', 'neck', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('épaule', 'shoulder', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('bras', 'arm', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('main', 'hand', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('doigt', 'finger', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('ventre', 'belly', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('jambe', 'leg', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('pied', 'foot', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('genou', 'knee', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('dos', 'back', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('cœur', 'heart', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('peau', 'skin', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('cheveu', 'hair', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('visage', 'face', 'A1');

-- 問候與基本用語（15）
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('bonjour', 'hello / good morning', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('bonsoir', 'good evening', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('bonne nuit', 'good night', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('au revoir', 'goodbye', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('salut', 'hi / bye', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('merci', 'thank you', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('s''il vous plaît', 'please', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('pardon', 'pardon / sorry', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('excusez-moi', 'excuse me', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('oui', 'yes', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('non', 'no', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('peut-être', 'maybe', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('voilà', 'there it is', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('voici', 'here is', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('bienvenue', 'welcome', 'A1');

-- 基礎動詞（40）
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('être', 'to be', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('avoir', 'to have', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('faire', 'to do / to make', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('aller', 'to go', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('venir', 'to come', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('voir', 'to see', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('dire', 'to say / to tell', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('prendre', 'to take', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('savoir', 'to know (a fact)', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('pouvoir', 'to be able to', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('vouloir', 'to want', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('aimer', 'to like / to love', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('manger', 'to eat', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('boire', 'to drink', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('parler', 'to speak', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('écrire', 'to write', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('lire', 'to read', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('dormir', 'to sleep', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('travailler', 'to work', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('jouer', 'to play', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('acheter', 'to buy', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('vendre', 'to sell', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('ouvrir', 'to open', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('fermer', 'to close', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('partir', 'to leave', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('arriver', 'to arrive', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('rentrer', 'to return home', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('chercher', 'to look for', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('trouver', 'to find', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('donner', 'to give', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('appeler', 'to call', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('écouter', 'to listen', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('regarder', 'to watch / to look at', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('penser', 'to think', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('habiter', 'to live in a place', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('marcher', 'to walk', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('courir', 'to run', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('rire', 'to laugh', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('pleurer', 'to cry', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('chanter', 'to sing', 'A1');

-- 基礎形容詞（30）注意：froid 也屬天氣，但只保留在此處一次
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('grand', 'big / tall', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('petit', 'small / little', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('bon', 'good', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('mauvais', 'bad', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('beau', 'beautiful / handsome', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('joli', 'pretty', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('laid', 'ugly', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('jeune', 'young', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('vieux', 'old', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('nouveau', 'new', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('haut', 'high / tall', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('bas', 'low', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('long', 'long', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('court', 'short', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('large', 'wide', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('étroit', 'narrow', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('chaud', 'hot / warm', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('froid', 'cold', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('rapide', 'fast', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('lent', 'slow', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('fort', 'strong', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('faible', 'weak', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('content', 'happy / pleased', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('triste', 'sad', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('fatigué', 'tired', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('malade', 'sick / ill', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('libre', 'free', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('occupé', 'busy', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('difficile', 'difficult', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('facile', 'easy', 'A1');

-- 地點（25）
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('maison', 'house / home', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('école', 'school', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('ville', 'city / town', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('pays', 'country', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('rue', 'street', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('route', 'road', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('place', 'square / plaza', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('parc', 'park', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('jardin', 'garden', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('forêt', 'forest', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('montagne', 'mountain', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('mer', 'sea', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('rivière', 'river', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('hôpital', 'hospital', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('magasin', 'shop / store', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('restaurant', 'restaurant', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('hôtel', 'hotel', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('gare', 'train station', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('aéroport', 'airport', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('musée', 'museum', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('église', 'church', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('bibliothèque', 'library', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('cinéma', 'cinema / movie theater', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('supermarché', 'supermarket', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('marché', 'market', 'A1');

-- 家居物品（30）
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('table', 'table', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('chaise', 'chair', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('lit', 'bed', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('armoire', 'wardrobe', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('porte', 'door', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('fenêtre', 'window', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('mur', 'wall', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('sol', 'floor', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('plafond', 'ceiling', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('lampe', 'lamp', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('télévision', 'television', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('ordinateur', 'computer', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('téléphone', 'telephone / phone', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('livre', 'book', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('cahier', 'notebook', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('stylo', 'pen', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('clé', 'key', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('sac', 'bag', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('valise', 'suitcase', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('miroir', 'mirror', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('tapis', 'rug / carpet', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('rideau', 'curtain', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('coussin', 'cushion / pillow', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('assiette', 'plate', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('verre', 'glass', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('tasse', 'cup / mug', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('cuillère', 'spoon', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('fourchette', 'fork', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('couteau', 'knife', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('casserole', 'saucepan', 'A1');

-- 天氣（14）注意：froid 已在形容詞
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('soleil', 'sun', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('pluie', 'rain', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('neige', 'snow', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('vent', 'wind', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('nuage', 'cloud', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('orage', 'thunderstorm', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('brouillard', 'fog', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('temps', 'weather / time', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('météo', 'weather forecast', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('tempête', 'storm', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('foudre', 'lightning', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('grêle', 'hail', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('arc-en-ciel', 'rainbow', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('chaleur', 'heat', 'A1');

-- 衣物（20）
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('robe', 'dress', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('pantalon', 'trousers / pants', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('chemise', 'shirt', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('veste', 'jacket', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('manteau', 'coat', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('chaussure', 'shoe', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('chaussette', 'sock', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('chapeau', 'hat', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('écharpe', 'scarf', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('gant', 'glove', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('cravate', 'tie', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('jean', 'jeans', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('pull', 'jumper / sweater', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('tee-shirt', 'T-shirt', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('jupe', 'skirt', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('maillot', 'swimsuit / jersey', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('ceinture', 'belt', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('sac à main', 'handbag', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('lunettes', 'glasses', 'A1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('montre', 'watch', 'A1');

-- ============================================================
-- A2 Words (175 筆)
-- ============================================================

-- A2 動詞（48）
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('apprendre', 'to learn', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('comprendre', 'to understand', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('connaître', 'to know a person/place', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('croire', 'to believe', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('devoir', 'to have to / must', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('entendre', 'to hear', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('sentir', 'to feel / to smell', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('mettre', 'to put', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('tenir', 'to hold', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('vivre', 'to live', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('attendre', 'to wait', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('remplir', 'to fill', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('choisir', 'to choose', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('finir', 'to finish', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('commencer', 'to begin / to start', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('continuer', 'to continue', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('arrêter', 'to stop', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('décider', 'to decide', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('demander', 'to ask', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('répondre', 'to answer / to reply', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('expliquer', 'to explain', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('montrer', 'to show', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('suivre', 'to follow', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('porter', 'to carry / to wear', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('tomber', 'to fall', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('lever', 'to lift / to raise', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('baisser', 'to lower', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('sortir', 'to go out', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('entrer', 'to enter', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('payer', 'to pay', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('aider', 'to help', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('permettre', 'to allow / to permit', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('sembler', 'to seem', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('paraître', 'to appear / to seem', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('devenir', 'to become', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('rester', 'to stay / to remain', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('naître', 'to be born', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('mourir', 'to die', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('grandir', 'to grow up', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('maigrir', 'to lose weight', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('grossir', 'to gain weight', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('perdre', 'to lose', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('gagner', 'to win / to earn', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('voyager', 'to travel', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('visiter', 'to visit', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('changer', 'to change', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('réserver', 'to book / to reserve', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('utiliser', 'to use', 'A2');

-- A2 名詞（48）注意：fille/femme 已在 A1 家庭
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('solution', 'solution', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('question', 'question', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('réponse', 'answer / reply', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('idée', 'idea', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('exemple', 'example', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('histoire', 'story / history', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('monde', 'world', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('vie', 'life', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('gens', 'people', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('personne', 'person', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('homme', 'man', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('garçon', 'boy', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('ami', 'friend (male)', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('voisin', 'neighbour', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('collègue', 'colleague', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('chef', 'boss / chef', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('client', 'customer / client', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('lettre', 'letter', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('message', 'message', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('journal', 'newspaper / diary', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('magazine', 'magazine', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('chanson', 'song', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('film', 'film / movie', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('jeu', 'game', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('sport', 'sport', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('football', 'football / soccer', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('tennis', 'tennis', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('natation', 'swimming', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('cuisine', 'cooking / kitchen', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('voyage', 'trip / travel', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('vacances', 'holidays / vacation', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('argent', 'money / silver', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('prix', 'price / prize', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('billet', 'ticket / banknote', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('ticket', 'ticket', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('cadeau', 'gift / present', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('souhait', 'wish', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('rêve', 'dream', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('peur', 'fear', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('bonheur', 'happiness', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('joie', 'joy', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('chance', 'luck / chance', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('aide', 'help', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('conseil', 'advice', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('problème', 'problem', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('différence', 'difference', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('résultat', 'result', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('groupe', 'group', 'A2');

-- A2 形容詞（40）
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('intelligent', 'intelligent / smart', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('bête', 'stupid', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('généreux', 'generous', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('avare', 'miserly / greedy', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('gentil', 'kind / nice', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('méchant', 'mean / naughty', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('sympa', 'nice / friendly', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('poli', 'polite', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('impoli', 'impolite / rude', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('courageux', 'brave / courageous', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('timide', 'shy / timid', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('nerveux', 'nervous', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('calme', 'calm', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('sérieux', 'serious', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('amusant', 'amusing / fun', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('drôle', 'funny', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('ennuyeux', 'boring', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('intéressant', 'interesting', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('utile', 'useful', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('inutile', 'useless', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('propre', 'clean / own', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('sale', 'dirty', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('plein', 'full', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('vide', 'empty', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('lourd', 'heavy', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('léger', 'light (weight)', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('riche', 'rich', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('pauvre', 'poor', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('heureux', 'happy', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('malheureux', 'unhappy', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('possible', 'possible', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('impossible', 'impossible', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('vrai', 'true / real', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('faux', 'false / wrong', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('prochain', 'next', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('dernier', 'last / latest', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('même', 'same / even', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('autre', 'other', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('seul', 'alone / only', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('ensemble', 'together', 'A2');

-- A2 交通工具（14）
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('voiture', 'car', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('bus', 'bus', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('train', 'train', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('avion', 'airplane', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('bateau', 'boat / ship', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('vélo', 'bicycle', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('moto', 'motorbike', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('taxi', 'taxi', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('tramway', 'tram', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('métro', 'underground / subway', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('camion', 'truck / lorry', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('ambulance', 'ambulance', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('scooter', 'scooter', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('trottinette', 'kick scooter', 'A2');

-- A2 職業（25）
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('médecin', 'doctor', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('infirmier', 'nurse (male)', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('professeur', 'teacher / professor', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('avocat', 'lawyer', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('ingénieur', 'engineer', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('architecte', 'architect', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('cuisinier', 'cook', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('serveur', 'waiter', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('vendeur', 'salesperson', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('caissier', 'cashier', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('policier', 'police officer', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('pompier', 'firefighter', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('acteur', 'actor', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('chanteur', 'singer', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('danseur', 'dancer', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('journaliste', 'journalist', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('photographe', 'photographer', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('musicien', 'musician', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('peintre', 'painter', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('écrivain', 'writer / author', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('directeur', 'director / manager', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('secrétaire', 'secretary', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('étudiant', 'student (university)', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('élève', 'pupil / student (school)', 'A2');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('agriculteur', 'farmer', 'A2');

-- ============================================================
-- B1 Words (101 筆)
-- ============================================================

-- B1 動詞（50）
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('améliorer', 'to improve', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('développer', 'to develop', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('réussir', 'to succeed', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('échouer', 'to fail', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('proposer', 'to propose / to suggest', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('accepter', 'to accept', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('refuser', 'to refuse', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('confirmer', 'to confirm', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('annuler', 'to cancel', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('préparer', 'to prepare', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('organiser', 'to organise', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('participer', 'to participate', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('représenter', 'to represent', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('produire', 'to produce', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('construire', 'to build / to construct', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('détruire', 'to destroy', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('protéger', 'to protect', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('défendre', 'to defend', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('attaquer', 'to attack', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('mentir', 'to lie', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('admettre', 'to admit', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('reconnaître', 'to recognise', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('éviter', 'to avoid', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('risquer', 'to risk', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('mériter', 'to deserve', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('dépendre', 'to depend', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('appartenir', 'to belong', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('ressembler', 'to resemble / to look like', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('imaginer', 'to imagine', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('inventer', 'to invent', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('découvrir', 'to discover', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('explorer', 'to explore', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('analyser', 'to analyse', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('évaluer', 'to evaluate', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('comparer', 'to compare', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('mesurer', 'to measure', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('calculer', 'to calculate', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('planifier', 'to plan', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('réaliser', 'to realise / to achieve', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('accomplir', 'to accomplish', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('satisfaire', 'to satisfy', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('décevoir', 'to disappoint', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('surprendre', 'to surprise', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('inquiéter', 'to worry', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('rassurer', 'to reassure', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('encourager', 'to encourage', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('critiquer', 'to criticise', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('approuver', 'to approve', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('hésiter', 'to hesitate', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('insister', 'to insist', 'B1');

-- B1 名詞（51）
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('gouvernement', 'government', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('société', 'society / company', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('économie', 'economy', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('politique', 'politics / policy', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('culture', 'culture', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('religion', 'religion', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('environnement', 'environment', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('technologie', 'technology', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('énergie', 'energy', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('ressource', 'resource', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('avantage', 'advantage', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('inconvénient', 'disadvantage', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('conséquence', 'consequence', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('raison', 'reason', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('cause', 'cause', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('effet', 'effect', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('début', 'beginning', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('fin', 'end', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('progrès', 'progress', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('développement', 'development', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('croissance', 'growth', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('crise', 'crisis', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('conflit', 'conflict', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('accord', 'agreement', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('contrat', 'contract', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('loi', 'law', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('règlement', 'regulation / rules', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('droit', 'right / law', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('liberté', 'freedom / liberty', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('responsabilité', 'responsibility', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('qualité', 'quality', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('valeur', 'value', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('attitude', 'attitude', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('comportement', 'behaviour', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('habitude', 'habit', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('tradition', 'tradition', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('coutume', 'custom', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('opinion', 'opinion', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('point de vue', 'point of view', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('argument', 'argument', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('preuve', 'proof / evidence', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('étude', 'study', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('recherche', 'research', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('expérience', 'experience', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('compétence', 'skill / competence', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('capacité', 'capacity / ability', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('effort', 'effort', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('succès', 'success', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('échec', 'failure', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('objectif', 'objective / goal', 'B1');
INSERT OR IGNORE INTO fallback_words(french, english, cefr_level) VALUES('stratégie', 'strategy', 'B1');
